### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by dborkan** [igarape/copcast-server#92]
Seeing this error on the copcast-server from today July 6, 2016:
```
TypeError: Cannot read property 'id' of undefined
    at Object.removeAdminByUserId (/copcast/projects/copcast-server/lib/streams/connectionManager.js:30:50)
    at Socket.<anonymous> (/copcast/projects/copcast-server/lib/streams/socketHandler.js:155:15)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/copcast/projects/copcast-server/node_modules/socket.io/lib/socket.js:128:10)
    at Socket.onclose (/copcast/projects/copcast-server/node_modules/socket.io/lib/socket.js:425:8)
    at Client.onclose (/copcast/projects/copcast-server/node_modules/socket.io/lib/client.js:232:24)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/copcast/projects/copcast-server/node_modules/socket.io/node_modules/engine.io/lib/socket.js:304:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.emit (events.js:92:17)
    at WebSocket.Transport.onClose (/copcast/projects/copcast-server/node_modules/socket.io/node_modules/engine.io/lib/transport.js:126:8)
    at WebSocket.g (events.js:180:16)
    at WebSocket.emit (events.js:98:17)
    at WebSocket.cleanupWebsocketResources (/copcast/projects/copcast-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:927:10)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by dborkan** [comment]
I believe this occurred when I refreshed the admin console

**Comment by arthurvasconcelos** [comment]
@dborkan do you have a step by step on how to reproduce?
